arch: amd64
os: linux
dist: trusty

language: node_js
node_js:
  - "14"


jobs: 
  fast_finish: true
  include:
    - stage: dependencies
    - name: "installing dependencies"
    - script: npm install
    - stage: prettier
    - name:  "prettier check"
    - script: npm run prettier-check
    - stage: eslint
    - name:  "eslint check"
    - script: npm run eslint
    - stage: build
    - name:  "build"
    - script: npm run build
 



