arch: amd64
os: linux
dist: trusty

language: node_js
node_js:
  - "14"


jobs: 
  fast_finish: true
  
before_install:
  - npm install -g typescript

install:
  - make build-typescript

eslint:
  - make eslint-tslint


