arch: amd64
os: linux
dist: trusty

language: node_js
node_js:
  - "14"
  
install:
  - npm install
  - npm install -g typescript

script:
  - npm run eslint
  - npm run prettier-check

build:
  - npm run build


