name: Deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.DEPLOYMENT_KEY }}" > "$HOME/.ssh/key"
    - run: chmod 600 "$HOME/.ssh/key"

    
    - run: npm ci
    - run: npm run build
    - run: cd static && sudo rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --omit-dir-times --no-perms --delete . clown@drip.monkeys.team:~/../fro/static/
    
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            Commit message: ${{ github.event.commits[0].message }}
              
              Repository: ${{ github.repository }}
              Continious deployment of ${{ github.event.commits[0].message }} ended
              GitHub checks: https://github.com/go-park-mail-ru/2021_2_MonKeys/commit/${{github.sha}}/checks
              Deploy link: https://drip.monkeys.team
  
